In [3]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [4]:
reviews = ['nice food',
            'amazing restaurant',
            'too good',
            'just loved it!',
            'will go again',
            'horrible food',
            'never go there',
            'poor service',
            'poor quality',
            'needs improvement']
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [5]:
one_hot('amazing restaurant', 30)

[13, 28]

In [6]:
vocab_size = 30

encoded_reviews =  [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[23, 11],
 [13, 28],
 [28, 17],
 [8, 23, 24],
 [28, 29, 17],
 [9, 11],
 [19, 29, 26],
 [14, 1],
 [14, 22],
 [24, 26]]

In [16]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen= max_length, padding = 'post')
print(padded_reviews)

[[23 11  0]
 [13 28  0]
 [28 17  0]
 [ 8 23 24]
 [28 29 17]
 [ 9 11  0]
 [19 29 26]
 [14  1  0]
 [14 22  0]
 [24 26  0]]


In [20]:
embedded_vector_size = 4
model = Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, input_length=max_length, name= 'embedding'))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [21]:
X = padded_reviews
y = sentiment

In [22]:
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten_1 (Flatten)         (None, 12)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 13        
                                                                 
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________


In [23]:
model.fit(X,y, epochs= 50, verbose= 0)

2024-02-09 09:25:10.939287: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2024-02-09 09:25:11.140868: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
loc("mps_select"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/0032d1ee-80fd-11ee-8227-6aecfccc70fe/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":294:0)): error: 'anec.gain_offset_control' op result #0 must be 4D/5D memref of 16-bit float or 8-bit signed integer or 8-bit unsigned integer values, but got 'memref<1x10x1x1xi1>'
loc("mps_select"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/0032d1ee-80fd-11ee-8227-6aecfccc70fe/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":294:0)): error: 'anec.gain_offset_control' op result #0 must be

In [24]:
loss, accuracy = model.evaluate(X,y)
accuracy

1/1 [==============================] - 0s 152ms/step - loss: 0.6324 - accuracy: 0.9000


2024-02-09 09:25:47.487451: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
loc("mps_select"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/0032d1ee-80fd-11ee-8227-6aecfccc70fe/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":294:0)): error: 'anec.gain_offset_control' op result #0 must be 4D/5D memref of 16-bit float or 8-bit signed integer or 8-bit unsigned integer values, but got 'memref<1x10x1x1xi1>'
loc("mps_select"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/0032d1ee-80fd-11ee-8227-6aecfccc70fe/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":294:0)): error: 'anec.gain_offset_control' op result #0 must be 4D/5D memref of 16-bit float or 8-bit signed integer or 8-bit unsigned integer values, but got 'memref<1x10x1x1xi1>'


0.8999999761581421

In [26]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [27]:
weights[23] # 23 is 'nice'

array([ 0.04872479, -0.01955344,  0.02047277,  0.04669799], dtype=float32)

In [28]:
weights[13] #13 is 'amazing'

array([-0.02673069,  0.04257019,  0.08303273, -0.08022892], dtype=float32)