In [3]:
!pip install tensorflow_hub
!pip install tensorflow_text

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 22.2 MB/s eta 0:00:00


In [4]:
import tensorflow_hub as hub
import tensorflow_text as text

In [5]:
preprocessor_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'
preprocessor = hub.KerasLayer(preprocessor_url)
encoder_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'
encoder = hub.KerasLayer(encoder_url)

In [8]:
text_test = ['nice movie indeed', 'I love python programming']
text_preprocessed = preprocessor(text_test)
text_preprocessed.keys()

dict_keys(['input_mask', 'input_type_ids', 'input_word_ids'])

In [10]:
text_preprocessed['input_mask']
#CLS nice movie indeed SEP

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

In [11]:
text_preprocessed['input_word_ids']
#CLS nice movie indeed SEP

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3835,  3185,  5262,   102,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [12]:
encoder_result = encoder(text_preprocessed)
encoder_result.keys()

dict_keys(['sequence_output', 'encoder_outputs', 'default', 'pooled_output'])

In [13]:
encoder_result['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.791774  , -0.21411912,  0.49769545, ...,  0.24465235,
        -0.47334474,  0.8175869 ],
       [-0.9171231 , -0.4793518 , -0.78656983, ..., -0.6175178 ,
        -0.7102687 ,  0.92184305]], dtype=float32)>

In [14]:
encoder_result['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292055,  0.08567822,  0.14476831, ..., -0.0967709 ,
          0.08722139,  0.07711068],
        [ 0.17839365, -0.19006082,  0.5034951 , ..., -0.05869842,
          0.3271711 , -0.15578556],
        [ 0.18701443, -0.43388733, -0.48875216, ..., -0.15502742,
          0.00145182, -0.24470933],
        ...,
        [ 0.12083032,  0.1288427 ,  0.46453518, ...,  0.07375532,
          0.17441945,  0.16522188],
        [ 0.07967904, -0.01190669,  0.5022545 , ...,  0.13777721,
          0.21002236,  0.00624595],
        [-0.07212678, -0.28303453,  0.5903338 , ...,  0.47551897,
          0.16668475, -0.0892035 ]],

       [[-0.07900588,  0.3633512 , -0.21101615, ..., -0.17183745,
          0.16299728,  0.6724266 ],
        [ 0.27883428,  0.43716276, -0.35764802, ..., -0.04463619,
          0.38315177,  0.58879846],
        [ 1.2037671 ,  1.0727018 ,  0.48408794, ...,  0.24921013,
          0.4073096 ,  0.40481815],
        ...,

In [15]:
len(encoder_result['encoder_outputs'])

12

In [16]:
encoder_result['encoder_outputs'][-1] == encoder_result['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=bool, numpy=
array([[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]],

       [[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True]]])>